I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 67, in script call
    $ renpy.call(target_label)
  File "game/labels/location/city.rpy", line 67, in script
    $ game.dragon.reputation.points += 5 + 3
  File "game/labels/location/city.rpy", line 67, in <module>
    $ game.dragon.reputation.points += 5 + 3
Exception: Cannot raise reputation. Invalid gain.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 67, in script call
    $ renpy.call(target_label)
  File "game/labels/location/city.rpy", line 67, in script
    $ game.dragon.reputation.points += 5 + 3
  File "/home/g2/Games/DefilerWings/DefilerWings-1.4.1-all-noteat2/renpy/ast.py", line 805, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/g2/Games/DefilerWings/DefilerWings-1.4.1-all-noteat2/renpy/python.py", line 1460, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/labels/location/city.rpy", line 67, in <module>
    $ game.dragon.reputation.points += 5 + 3
  File "/home/g2/Games/DefilerWings/DefilerWings-1.4.1-all-noteat2/renpy/python.py", line 546, in do_mutation
    return method(self, *args, **kwargs)
  File "/home/g2/Games/DefilerWings/DefilerWings-1.4.1-all-noteat2/renpy/python.py", line 710, in __setattr__
    object.__setattr__(self, attr, value)
  File "pythoncode/points.py", line 88, in points
Exception: Cannot raise reputation. Invalid gain.

Linux-5.15.0-88-generic-x86_64-with-debian-bookworm-sid
Ren'Py 6.99.7.858
Defiler Wings 1.4.1.fdsc
